WITH INCOME AS (
    SELECT XOCB.BRANCH_CODE|| '-' ||XOCB.BRANCH_NAME BRANCH
         , XOCB.PARENT_ORG ORGANIZATION
         , SUM(ACRA.AMOUNT) RECEIPT
    FROM XX_ORG_COMPANY_BRANCH_V XOCB
        , AR_CASH_RECEIPTS_ALL ACRA
    WHERE XOCB.ORG_ID = ACRA.ORG_ID
      AND ACRA.RECEIPT_DATE BETWEEN '01-AUG-2024' AND '31-AUG-2024'
    GROUP BY XOCB.BRANCH_CODE|| '-' ||XOCB.BRANCH_NAME
           , XOCB.PARENT_ORG
)
SELECT BRANCH
     , SUM(CASE WHEN ORGANIZATION = 'SCS' THEN RECEIPT ELSE 0 END) AS SCS_RECEIPT
     , SUM(CASE WHEN ORGANIZATION = 'SETS' THEN RECEIPT ELSE 0 END) AS SETS_RECEIPT
     , SUM(CASE WHEN ORGANIZATION = 'VD' THEN RECEIPT ELSE 0 END) AS VD_RECEIPT
FROM INCOME
GROUP BY BRANCH
ORDER BY BRANCH;

--******************

WITH EXPENSE
AS
(SELECT XOCB.BRANCH_CODE|| '-' ||XOCB.BRANCH_NAME BRANCH
         , XOCB.PARENT_ORG ORGANIZATION
         , SUM(AIPA.AMOUNT) EXPENSE
    FROM XX_ORG_COMPANY_BRANCH_V XOCB
        , AP_INVOICE_PAYMENTS_ALL AIPA
    WHERE XOCB.ORG_ID = AIPA.ORG_ID
      AND AIPA.accounting_date BETWEEN '01-AUG-2024' AND '31-AUG-2024'
    GROUP BY XOCB.BRANCH_CODE|| '-' ||XOCB.BRANCH_NAME
           , XOCB.PARENT_ORG)
SELECT BRANCH
      , SUM(CASE WHEN ORGANIZATION = 'SCS' THEN EXPENSE ELSE 0 END) AS SCS_EXPENSE
      , SUM(CASE WHEN ORGANIZATION = 'SETS' THEN EXPENSE ELSE 0 END) AS SETS_EXPENSE
      , SUM(CASE WHEN ORGANIZATION = 'VD' THEN EXPENSE ELSE 0 END) AS VD_EXPENSE
FROM EXPENSE
GROUP BY BRANCH
ORDER BY BRANCH;

--**********************************

WITH INCOME AS (
    SELECT XOCB.BRANCH_CODE|| '-' ||XOCB.BRANCH_NAME BRANCH
         , XOCB.PARENT_ORG ORGANIZATION
         , SUM(ACRA.AMOUNT) RECEIPT
    FROM XX_ORG_COMPANY_BRANCH_V XOCB
        , AR_CASH_RECEIPTS_ALL ACRA
    WHERE XOCB.ORG_ID = ACRA.ORG_ID
      AND ACRA.RECEIPT_DATE BETWEEN '01-AUG-2024' AND '31-AUG-2024'
    GROUP BY XOCB.BRANCH_CODE|| '-' ||XOCB.BRANCH_NAME
           , XOCB.PARENT_ORG),
EXPENSE AS
(SELECT XOCB.BRANCH_CODE|| '-' ||XOCB.BRANCH_NAME BRANCH
         , XOCB.PARENT_ORG ORGANIZATION
         , SUM(AIPA.AMOUNT) EXPENSE
    FROM XX_ORG_COMPANY_BRANCH_V XOCB
        , AP_INVOICE_PAYMENTS_ALL AIPA
    WHERE XOCB.ORG_ID = AIPA.ORG_ID
      AND AIPA.accounting_date BETWEEN '01-AUG-2024' AND '31-AUG-2024'
    GROUP BY XOCB.BRANCH_CODE|| '-' ||XOCB.BRANCH_NAME
           , XOCB.PARENT_ORG)
SELECT I.BRANCH
     , SUM(CASE WHEN I.ORGANIZATION = 'SCS' THEN I.RECEIPT ELSE 0 END) AS SCS_RECEIPT
	 , SUM(CASE WHEN E.ORGANIZATION = 'SCS' THEN E.EXPENSE ELSE 0 END) AS SCS_EXPENSE
     , SUM(CASE WHEN I.ORGANIZATION = 'SETS' THEN I.RECEIPT ELSE 0 END) AS SETS_RECEIPT
	 , SUM(CASE WHEN E.ORGANIZATION = 'SETS' THEN E.EXPENSE ELSE 0 END) AS SETS_EXPENSE
     , SUM(CASE WHEN I.ORGANIZATION = 'VD' THEN I.RECEIPT ELSE 0 END) AS VD_RECEIPT
	 , SUM(CASE WHEN E.ORGANIZATION = 'VD' THEN E.EXPENSE ELSE 0 END) AS VD_EXPENSE
FROM INCOME I
    , EXPENSE E
WHERE I.BRANCH = E.BRANCH 
  AND I.ORGANIZATION = E.ORGANIZATION
GROUP BY I.BRANCH
ORDER BY 1;