CREATE OR REPLACE PACKAGE APPS.AP_AI_TABLE_HANDLER_PKG AUTHID CURRENT_USER as
/* $Header: apainths.pls 120.15.12010000.5 2009/09/22 11:01:03 baole ship $ */

PROCEDURE Insert_Row(
          p_Rowid                       IN OUT NOCOPY VARCHAR2,
          p_Invoice_Id                  IN OUT NOCOPY NUMBER,
          p_Last_Update_Date                   DATE,
          p_Last_Updated_By                    NUMBER,
          p_Vendor_Id                          NUMBER,
          p_Invoice_Num                        VARCHAR2,
          p_Invoice_Amount                     NUMBER,
          p_Vendor_Site_Id                     NUMBER,
          p_Amount_Paid                        NUMBER,
          p_Discount_Amount_Taken              NUMBER,
          p_Invoice_Date                       DATE,
          p_Source                             VARCHAR2,
          p_Invoice_Type_Lookup_Code           VARCHAR2,
          p_Description                        VARCHAR2,
          p_Batch_Id                           NUMBER,
          p_Amt_Applicable_To_Discount         NUMBER,
          p_Terms_Id                           NUMBER,
          p_Terms_Date                         DATE,
          p_Goods_Received_Date                DATE,
          p_Invoice_Received_Date              DATE,
          p_Voucher_Num                        VARCHAR2,
          p_Approved_Amount                    NUMBER,
          p_Approval_Status                    VARCHAR2,
          p_Approval_Description               VARCHAR2,
          p_Pay_Group_Lookup_Code              VARCHAR2,
          p_Set_Of_Books_Id                    NUMBER,
          p_Accts_Pay_CCId                     NUMBER,
          p_Recurring_Payment_Id               NUMBER,
          p_Invoice_Currency_Code              VARCHAR2,
          p_Payment_Currency_Code              VARCHAR2,
          p_Exchange_Rate                      NUMBER,
          p_Payment_Amount_Total               NUMBER,
          p_Payment_Status_Flag                VARCHAR2,
          p_Posting_Status                     VARCHAR2,
          p_Authorized_By                      VARCHAR2,
          p_Attribute_Category                 VARCHAR2,
          p_Attribute1                         VARCHAR2,
          p_Attribute2                         VARCHAR2,
          p_Attribute3                         VARCHAR2,
          p_Attribute4                         VARCHAR2,
          p_Attribute5                         VARCHAR2,
          p_Creation_Date                      DATE,
          p_Created_By                         NUMBER,
          p_Vendor_Prepay_Amount               NUMBER,
          p_Base_Amount                        NUMBER,
          p_Exchange_Rate_Type                 VARCHAR2,
          p_Exchange_Date                      DATE,
          p_Payment_Cross_Rate                 NUMBER,
          p_Payment_Cross_Rate_Type            VARCHAR2,
          p_Payment_Cross_Rate_Date            Date,
          p_Pay_Curr_Invoice_Amount            NUMBER,
          p_Last_Update_Login                  NUMBER,
          p_Original_Prepayment_Amount         NUMBER,
          p_Earliest_Settlement_Date           DATE,
          p_Attribute11                        VARCHAR2,
          p_Attribute12                        VARCHAR2,
          p_Attribute13                        VARCHAR2,
          p_Attribute14                        VARCHAR2,
          p_Attribute6                         VARCHAR2,
          p_Attribute7                         VARCHAR2,
          p_Attribute8                         VARCHAR2,
          p_Attribute9                         VARCHAR2,
          p_Attribute10                        VARCHAR2,
          p_Attribute15                        VARCHAR2,
          p_Cancelled_Date                     DATE,
          p_Cancelled_By                       NUMBER,
          p_Cancelled_Amount                   NUMBER,
          p_Temp_Cancelled_Amount              NUMBER,
          p_Exclusive_Payment_Flag             VARCHAR2,
          p_Po_Header_Id                       NUMBER,
          p_Doc_Sequence_Id                    NUMBER,
          p_Doc_Sequence_Value                 NUMBER,
          p_Doc_Category_Code                  VARCHAR2,
          p_Expenditure_Item_Date              DATE,
          p_Expenditure_Organization_Id        NUMBER,
          p_Expenditure_Type                   VARCHAR2,
          p_Pa_Default_Dist_Ccid               NUMBER,
          p_Pa_Quantity                        NUMBER,
          p_Project_Id                         NUMBER,
          p_Task_Id                            NUMBER,
          p_Awt_Flag                           VARCHAR2,
          p_Awt_Group_Id                       NUMBER,
          p_Pay_Awt_Group_Id                       NUMBER, --bug6639866
          p_Reference_1                        VARCHAR2,
          p_Reference_2                        VARCHAR2,
          p_Org_Id                             NUMBER,
          p_global_attribute_category          VARCHAR2 DEFAULT NULL,
          p_global_attribute1                  VARCHAR2 DEFAULT NULL,
          p_global_attribute2                  VARCHAR2 DEFAULT NULL,
          p_global_attribute3                  VARCHAR2 DEFAULT NULL,
          p_global_attribute4                  VARCHAR2 DEFAULT NULL,
          p_global_attribute5                  VARCHAR2 DEFAULT NULL,
          p_global_attribute6                  VARCHAR2 DEFAULT NULL,
          p_global_attribute7                  VARCHAR2 DEFAULT NULL,
          p_global_attribute8                  VARCHAR2 DEFAULT NULL,
          p_global_attribute9                  VARCHAR2 DEFAULT NULL,
          p_global_attribute10                 VARCHAR2 DEFAULT NULL,
          p_global_attribute11                 VARCHAR2 DEFAULT NULL,
          p_global_attribute12                 VARCHAR2 DEFAULT NULL,
          p_global_attribute13                 VARCHAR2 DEFAULT NULL,
          p_global_attribute14                 VARCHAR2 DEFAULT NULL,
          p_global_attribute15                 VARCHAR2 DEFAULT NULL,
          p_global_attribute16                 VARCHAR2 DEFAULT NULL,
          p_global_attribute17                 VARCHAR2 DEFAULT NULL,
          p_global_attribute18                 VARCHAR2 DEFAULT NULL,
          p_global_attribute19                 VARCHAR2 DEFAULT NULL,
          p_global_attribute20                 VARCHAR2 DEFAULT NULL,
          p_calling_sequence            IN     VARCHAR2,
          p_gl_date                            DATE,
          p_Award_Id                           NUMBER,
          p_approval_iteration                 NUMBER,
          p_approval_ready_flag                VARCHAR2 DEFAULT 'Y',
          p_wfapproval_status                  VARCHAR2 DEFAULT 'NOT REQUIRED',
          p_paid_on_behalf_employee_id         NUMBER   DEFAULT NULL,
          p_amt_due_employee                   NUMBER   DEFAULT NULL,
          p_amt_due_ccard_company              NUMBER   DEFAULT NULL,
          p_requester_id                       NUMBER   DEFAULT NULL,
          -- Invoice Lines Project Stage 1
          p_quick_credit                       VARCHAR2 DEFAULT NULL,
          p_credited_invoice_id                NUMBER   DEFAULT NULL,
          p_distribution_set_id                NUMBER   DEFAULT NULL,
	  --Etax: Invwkb
	  p_force_revalidation_flag	       VARCHAR2 DEFAULT NULL,
	  p_control_amount                     NUMBER   DEFAULT NULL,
	  p_tax_related_invoice_id             NUMBER   DEFAULT NULL,
	  p_trx_business_category              VARCHAR2 DEFAULT NULL,
	  p_user_defined_fisc_class            VARCHAR2 DEFAULT NULL,
	  p_taxation_country                   VARCHAR2 DEFAULT NULL,
	  p_document_sub_type                  VARCHAR2 DEFAULT NULL,
	  p_supplier_tax_invoice_number        VARCHAR2 DEFAULT NULL,
	  p_supplier_tax_invoice_date          DATE     DEFAULT NULL,
	  p_supplier_tax_exchange_rate         NUMBER   DEFAULT NULL,
	  p_tax_invoice_recording_date         DATE     DEFAULT NULL,
	  p_tax_invoice_internal_seq           VARCHAR2 DEFAULT NULL, -- bug 8912305: modify
	  p_legal_entity_id		       NUMBER   DEFAULT NULL,
	  p_quick_po_header_id		       NUMBER   DEFAULT NULL,
          P_PAYMENT_METHOD_CODE                varchar2 ,
          P_PAYMENT_REASON_CODE                varchar2 default null,
          P_PAYMENT_REASON_COMMENTS            varchar2 default null,
          P_UNIQUE_REMITTANCE_IDENTIFIER       varchar2 default null,
          P_URI_CHECK_DIGIT                    varchar2 default null,
          P_BANK_CHARGE_BEARER                 varchar2 default null,
          P_DELIVERY_CHANNEL_CODE              varchar2 default null,
          P_SETTLEMENT_PRIORITY                varchar2 default null,
	  p_net_of_retainage_flag	       varchar2 default null,
	  p_release_amount_net_of_tax	       number   default null,
	  p_port_of_entry_code		       varchar2 default null,
          p_external_bank_account_id           number   default null,
          p_party_id                           number   default null,
          p_party_site_id                      number   default null,
           /* bug 4931755. Exclude Tax and Freight From Discount  */
          p_disc_is_inv_less_tax_flag          varchar2 default null,
          p_exclude_freight_from_disc          varchar2 default null,
          /* Bug 5087834 */
          p_remit_msg1                         varchar2 default null,
          p_remit_msg2                         varchar2 default null,
          p_remit_msg3                         varchar2 default null,
	  p_cust_registration_number	       varchar2 default null,
	  /* Third Party Payments*/
	  p_remit_to_supplier_name	varchar2 default null,
	  p_remit_to_supplier_id	number default null,
	  p_remit_to_supplier_site	varchar2 default null,
	  p_remit_to_supplier_site_id number default null,
	  p_relationship_id		number default null,
	  /* Bug 7831073 */
	  p_original_invoice_amount number default null,
	  p_dispute_reason varchar2 default null
	  );

PROCEDURE Update_Row(
          p_Rowid                              VARCHAR2,
          p_Invoice_Id                         NUMBER,
          p_Last_Update_Date                   DATE,
          p_Last_Updated_By                    NUMBER,
          p_Vendor_Id                          NUMBER,
          p_Invoice_Num                        VARCHAR2,
          p_Invoice_Amount                     NUMBER,
          p_Vendor_Site_Id                     NUMBER,
          p_Amount_Paid                        NUMBER,
          p_Discount_Amount_Taken              NUMBER,
          p_Invoice_Date                       DATE,
          p_Source                             VARCHAR2,
          p_Invoice_Type_Lookup_Code           VARCHAR2,
          p_Description                        VARCHAR2,
          p_Batch_Id                           NUMBER,
          p_Amt_Applicable_To_Discount         NUMBER,
          p_Terms_Id                           NUMBER,
          p_Terms_Date                         DATE,
          p_Goods_Received_Date                DATE,
          p_Invoice_Received_Date              DATE,
          p_Voucher_Num                        VARCHAR2,
          p_Approved_Amount                    NUMBER,
          p_Approval_Status                    VARCHAR2,
          p_Approval_Description               VARCHAR2,
          p_Pay_Group_Lookup_Code              VARCHAR2,
          p_Set_Of_Books_Id                    NUMBER,
          p_Accts_Pay_CCId                     NUMBER,
          p_Recurring_Payment_Id               NUMBER,
          p_Invoice_Currency_Code              VARCHAR2,
          p_Payment_Currency_Code              VARCHAR2,
          p_Exchange_Rate                      NUMBER,
          p_Payment_Amount_Total               NUMBER,
          p_Payment_Status_Flag                VARCHAR2,
          p_Posting_Status                     VARCHAR2,
          p_Authorized_By                      VARCHAR2,
          p_Attribute_Category                 VARCHAR2,
          p_Attribute1                         VARCHAR2,
          p_Attribute2                         VARCHAR2,
          p_Attribute3                         VARCHAR2,
          p_Attribute4                         VARCHAR2,
          p_Attribute5                         VARCHAR2,
          p_Vendor_Prepay_Amount               NUMBER,
          p_Base_Amount                        NUMBER,
          p_Exchange_Rate_Type                 VARCHAR2,
          p_Exchange_Date                      DATE,
          p_Payment_Cross_Rate                 NUMBER,
          p_Payment_Cross_Rate_Type            VARCHAR2,
          p_Payment_Cross_Rate_Date            DATE,
          p_Pay_Curr_Invoice_Amount            NUMBER,
          p_Last_Update_Login                  NUMBER,
          p_Original_Prepayment_Amount         NUMBER,
          p_Earliest_Settlement_Date           DATE,
          p_Attribute11                        VARCHAR2,
          p_Attribute12                        VARCHAR2,
          p_Attribute13                        VARCHAR2,
          p_Attribute14                        VARCHAR2,
          p_Attribute6                         VARCHAR2,
          p_Attribute7                         VARCHAR2,
          p_Attribute8                         VARCHAR2,
          p_Attribute9                         VARCHAR2,
          p_Attribute10                        VARCHAR2,
          p_Attribute15                        VARCHAR2,
          p_Cancelled_Date                     DATE,
          p_Cancelled_By                       NUMBER,
          p_Cancelled_Amount                   NUMBER,
          p_Temp_Cancelled_Amount              NUMBER,
          p_Exclusive_Payment_Flag             VARCHAR2,
          p_Po_Header_Id                       NUMBER,
          p_Doc_Sequence_Id                    NUMBER,
          p_Doc_Sequence_Value                 NUMBER,
          p_Doc_Category_Code                  VARCHAR2,
          p_Expenditure_Item_Date              DATE,
          p_Expenditure_Organization_Id        NUMBER,
          p_Expenditure_Type                   VARCHAR2,
          p_Pa_Default_Dist_Ccid               NUMBER,
          p_Pa_Quantity                        NUMBER,
          p_Project_Id                         NUMBER,
          p_Task_Id                            NUMBER,
          p_Awt_Flag                           VARCHAR2,
          p_Awt_Group_Id                       NUMBER,
          p_Pay_Awt_Group_Id                       NUMBER,--bug6639866
          p_Reference_1                        VARCHAR2,
          p_Reference_2                        VARCHAR2,
          p_Org_Id                             NUMBER,
          p_global_attribute_category          VARCHAR2 DEFAULT NULL,
          p_global_attribute1                  VARCHAR2 DEFAULT NULL,
          p_global_attribute2                  VARCHAR2 DEFAULT NULL,
          p_global_attribute3                  VARCHAR2 DEFAULT NULL,
          p_global_attribute4                  VARCHAR2 DEFAULT NULL,
          p_global_attribute5                  VARCHAR2 DEFAULT NULL,
          p_global_attribute6                  VARCHAR2 DEFAULT NULL,
          p_global_attribute7                  VARCHAR2 DEFAULT NULL,
          p_global_attribute8                  VARCHAR2 DEFAULT NULL,
          p_global_attribute9                  VARCHAR2 DEFAULT NULL,
          p_global_attribute10                 VARCHAR2 DEFAULT NULL,
          p_global_attribute11                 VARCHAR2 DEFAULT NULL,
          p_global_attribute12                 VARCHAR2 DEFAULT NULL,
          p_global_attribute13                 VARCHAR2 DEFAULT NULL,
          p_global_attribute14                 VARCHAR2 DEFAULT NULL,
          p_global_attribute15                 VARCHAR2 DEFAULT NULL,
          p_global_attribute16                 VARCHAR2 DEFAULT NULL,
          p_global_attribute17                 VARCHAR2 DEFAULT NULL,
          p_global_attribute18                 VARCHAR2 DEFAULT NULL,
          p_global_attribute19                 VARCHAR2 DEFAULT NULL,
          p_global_attribute20                 VARCHAR2 DEFAULT NULL,
          p_calling_sequence            IN     VARCHAR2,
          p_gl_date                            DATE,
          p_Award_Id                           NUMBER,
          p_approval_iteration                 NUMBER,
          p_approval_ready_flag                VARCHAR2 DEFAULT 'Y',
          p_wfapproval_status                  VARCHAR2 DEFAULT 'NOT REQUIRED',
          p_requester_id                       NUMBER   DEFAULT NULL,
          -- Invoice Lines Project Stage 1
          p_quick_credit                       VARCHAR2 DEFAULT NULL,
          p_credited_invoice_id                NUMBER   DEFAULT NULL,
          p_distribution_set_id                NUMBER   DEFAULT NULL,
	  --ETAX: Invwkb
	  p_force_revalidation_flag            VARCHAR2 DEFAULT NULL,
	  p_control_amount                     NUMBER   DEFAULT NULL,
	  p_tax_related_invoice_id             NUMBER   DEFAULT NULL,
	  p_trx_business_category              VARCHAR2 DEFAULT NULL,
	  p_user_defined_fisc_class            VARCHAR2 DEFAULT NULL,
	  p_taxation_country                   VARCHAR2 DEFAULT NULL,
	  p_document_sub_type                  VARCHAR2 DEFAULT NULL,
	  p_supplier_tax_invoice_number        VARCHAR2 DEFAULT NULL,
	  p_supplier_tax_invoice_date          DATE     DEFAULT NULL,
	  p_supplier_tax_exchange_rate         NUMBER   DEFAULT NULL,
	  p_tax_invoice_recording_date         DATE     DEFAULT NULL,
	  p_tax_invoice_internal_seq           VARCHAR2 DEFAULT NULL, -- bug 8912305: modify
	  p_quick_po_header_id		       NUMBER   DEFAULT NULL,
          P_PAYMENT_METHOD_CODE                varchar2 ,
          P_PAYMENT_REASON_CODE                varchar2 default null,
          P_PAYMENT_REASON_COMMENTS            varchar2 default null,
          P_UNIQUE_REMITTANCE_IDENTIFIER       varchar2 default null,
          P_URI_CHECK_DIGIT                    varchar2 default null,
          P_BANK_CHARGE_BEARER                 varchar2 default null,
          P_DELIVERY_CHANNEL_CODE              varchar2 default null,
          P_SETTLEMENT_PRIORITY                varchar2 default null,
	  p_net_of_retainage_flag	       varchar2 default null,
	  p_release_amount_net_of_tax	       number   default null,
	  p_port_of_entry_code		       varchar2 default null,
          p_external_bank_account_id           number   default null,
          p_party_id                           number   default null,
          p_party_site_id                      number   default null,
         /* bug 4931755 . Exclude Tax and Freight From Discount */
          p_disc_is_inv_less_tax_flag          varchar2 default null,
          p_exclude_freight_from_disc          varchar2 default null,
          -- Bug 5087834
          p_remit_msg1                         varchar2 default null,
          p_remit_msg2                         varchar2 default null,
          p_remit_msg3                         varchar2 default null,
	  /* Third Party Payments*/
	  p_remit_to_supplier_name	varchar2 default null,
	  p_remit_to_supplier_id	number default null,
	  p_remit_to_supplier_site	varchar2 default null,
	  p_remit_to_supplier_site_id number default null,
	  p_relationship_id		number default null,
	  /* Bug 7831073 */
	  p_original_invoice_amount number default null,
	  p_dispute_reason varchar2 default null
	  );

PROCEDURE Delete_Row(
          p_Rowid                              VARCHAR2,
          p_calling_sequence            IN     VARCHAR2);


END AP_AI_TABLE_HANDLER_PKG;
/
